version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wiki-search"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l23b0jbptx1"
s3_prefix = "wiki-search"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
